on:
  push:
    branches: [ main ]

name: Create Latest

jobs:

  ko-resolve:
    name: Release ko artifact
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: off
      KO_DOCKER_REPO: docker.io/vmware

    steps:
    - name: Set up Go 1.17.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GOOGLE_JSON_KEY }}

    - name: Setup ko
      run: |
        curl -L https://github.com/google/ko/releases/download/v0.8.3/ko_0.8.3_Linux_x86_64.tar.gz | tar xzf - ko
        chmod +x ./ko
        sudo mv ko /usr/local/bin
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Check out code onto GOPATH
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}

    - name: Build and Publish images, Produce release artifact.
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        ko resolve --platform=all --tags $(basename "${{ github.ref }}" ) -BRf config/ > release.yaml

        # This is the layout that the knative/website shortcode expects.
        gsutil cp release.yaml gs://vmware-tanzu-nightly/sources-for-knative/latest/release.yaml
